# Generated by Django 5.1.4 on 2025-01-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book_favorite_delete_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
