# Generated by Django 5.1.4 on 2025-01-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_favorite_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='cover_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
